### ISSUE TITLE
No module named `ts` in `fairseq_cli/train.py`

### ISSUE THREAD

**Issue by abkds** [facebookresearch/access#4] opened 2019-11-26 04:59 UTC
I tried to run the model and train it from scratch following the instructions given. I am getting the following error. 

```
| model transformer, criterion LabelSmoothedCrossEntropyCriterion
| num. model params: 59637760 (num. trained: 59637760)
| training on 1 GPUs
| max tokens per GPU = 5000 and max sentences per GPU = None
| no existing checkpoint found /home/ubuntu/access/experiments/fairseq/local_1574732696143/checkpoints/checkpoint_last.pt
| epoch 001:   1000 / 2567 loss=12.345, nll_loss=10.559, ppl=1508.20, wps=3578, ups=1, wpb=2960.115, bsz=115.516, num_updates=1001, lr=2.75275e-05, gnorm=1.459, clip=1.000, oom=0.000, wall=830, train_wall=820
| epoch 001:   2000 / 2567 loss=12.007, nll_loss=9.792, ppl=886.70, wps=3564, ups=1, wpb=2952.709, bsz=115.842, num_updates=2001, lr=5.50275e-05, gnorm=1.309, clip=1.000, oom=0.000, wall=1660, train_wall=1641
| epoch 001 | loss 11.877 | nll_loss 9.490 | ppl 719.11 | wps 3574 | ups 1 | wpb 2959.828 | bsz 115.466 | num_updates 2567 | lr 7.05925e-05 | gnorm 1.231 | clip 1.000 | oom 0.000 | wall 2128 | train_wall 2105
Traceback (most recent call last):
  File "scripts/train.py", line 49, in <module>
    fairseq_train_and_evaluate(**kwargs)
  File "/home/ubuntu/access/access/utils/training.py", line 18, in wrapped_func
    return func(*args, **kwargs)
  File "/home/ubuntu/access/access/utils/training.py", line 29, in wrapped_func
    return func(*args, **kwargs)
  File "/home/ubuntu/access/access/utils/training.py", line 38, in wrapped_func
    result = func(*args, **kwargs)
  File "/home/ubuntu/access/access/utils/training.py", line 50, in wrapped_func
    result = func(*args, **kwargs)
  File "/home/ubuntu/access/access/fairseq/main.py", line 121, in fairseq_train_and_evaluate
    fairseq_train(preprocessed_dir, exp_dir=exp_dir, **train_kwargs)
  File "/home/ubuntu/access/access/fairseq/base.py", line 175, in fairseq_train
    train.main(train_args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/fairseq_cli/train.py", line 111, in main
    valid_losses = sari_validate(args, trainer, task, epoch_itr, valid_subsets)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/fairseq_cli/train.py", line 272, in sari_validate
    from ts.resources.paths import get_data_filepath
ModuleNotFoundError: No module named 'ts'
```
Which module is this `ts` ? I understand that you are using a customized version of `fairseq_cli/train.py` which has `sari_validate` . Can you give me some pointers on how to resolve this issue?

Thanks

**Comment by louismartin** [comment] 2019-11-26 17:47
Hi @abkds ,

Good catch, actually ts should be access. Just try replacing the imports, I'll fix it soon!
However it might not fix the problem completely, I need to investigate.
This part is only used for early stopping on SARI actually so maybe all of it is not necessary.

**Comment by louismartin** [comment] 2019-12-08 18:48
I think it's fixed now if you reinstall fairseq with the special version, please reopen if the issue is still there.

**Closed by louismartin** 2019-12-08 18:48 UTC
